# Generated by Django 5.2.7 on 2025-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_post_category_post_created_at_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
